clustername: ""
consoleUrl: ""

checker:
  cluster:
    schedule: '"0 16 * * 1-4"'
  operator:
    schedule: '"0 7 * * MON"'
  successfulJobsHistoryLimit: 2
  suspend: false
  updateTime: "05"
  resources:
    limits:
      memory: "500Mi"
      cpu: "30m"
    requests:
      memory: "100Mi"
      cpu: "10m"
  desiredChannel: "stable"

updater:
  schedule: '"0 3 * * 2-5"'
  successfulJobsHistoryLimit: 2
  suspend: true
  delay: 1
  resources:
    limits:
      memory: "500Mi"
      cpu: "100m"
    requests:
      memory: "100Mi"
      cpu: "10m"

cleanup:
  schedule: '"0 16 * * 1-4"'
  successfulJobsHistoryLimit: 2
  suspend: false
  delay: 270
  resources:
    limits:
      memory: "500Mi"
      cpu: "100m"
    requests:
      memory: "100Mi"
      cpu: "10m"

slack:
  channel: ""
