apiVersion: redhatcop.redhat.io/v1alpha1
kind: ResourceLocker
metadata:
  name: label-openshift-config-ns-patch
spec:
  serviceAccountRef:
    name: resource-locker-sa
  patches:
  - targetObjectRef:
      apiVersion: v1
      kind: Namespace
      name: openshift-config
    patchTemplate: |
      metadata:
        labels:
          argocd.argoproj.io/managed-by: {{ .Release.Namespace }}
    patchType: application/strategic-merge-patch+json
    id: label-openshift-config-ns-patch