# Default values for gp-bke-runtime-minimal-application.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

# metadata.name: [RELEASE-NAME]-[nameOverride]
# metadata.label.app.kubernetes.io/name: [nameOverride]
nameOverride: ""

# metadata.name: [fullnameOverride]
# metadata.label.app.kubernetes.io/name: gp-bke-runtime-minimal-application
fullnameOverride: ""

image:
  # The name of the image to be used, e.g. image-registry.openshift-image-registry.svc.cluster.local:5000/example-project/example-backend
  name: 
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion
  tag: ""

ports: {}
  # - name: http
  #   containerPort: 8080
  #   protocol: TCP

podAnnotations: {}
  # annotation1: value1
  # annotation2: value2

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

route:
  # Deploy a route for this deployment?
  enabled: false
  # whether you want to explicitely set a hostname. if true, requires route.basename
  hostnameOverride: false
  # route.hostname if not defined and route.hostnameOverride .Release.Name will be applied
  # route.basename: apps.play.geplexx.com
  wildcardPolicy: None
  tls:
    enabled: true
    termination: edge

livenessProbe:
  enabled: false
  path: "" # default is /

readinessProbe:
  enabled: false
  path: "" # default is /

# Define environment variables for the pod
env: {}
  # - name: YOUR_ENV_NAME
  #   value: YOUR_ENV_VALUE

resources:
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 250m
    memory: 250Mi