apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  groups:
    - name: alertmanager-healthcheck
      rules:
        - alert: no_alertmanager_heartbeat
          annotations:
            description: >-
              Ein Alertmanager sendet keinen Status!
            summary: >-
              Vom Alertmanager auf {{ "{{" }} $labels.cluster_discriminator {{ "}}" }} wurde f√ºr 15min
              kein Status empfangen!
          expr: 'rate(alertmanager_health_checks_received[10m]) == 0'
          labels:
            severity: critical