# Default values for gp-bke-deploy-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

# metadata.name: [RELEASE-NAME]-[nameOverride]
# metadata.label.app.kubernetes.io/name: [nameOverride]
nameOverride: "mega-zep-backend"

# metadata.name: [fullnameOverride]
# metadata.label.app.kubernetes.io/name: gp-bke-deploy-app
fullnameOverride: "mega-zep-backend"

image:
  name: image-registry.openshift-image-registry.svc.cluster.local:5000/gattma-bke-tests/mega-backend
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 2e643ddee0e9c711a387e6640c38e4cbf6bed595

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

route:
  enabled: true
  wildcardPolicy: None
  tls:
    enabled: true
    termination: edge
    insecureEdgeTerminationPolicy: None
    ## IMPORTANT: Do not check 'key' into git!
    key:
    caCertificate:
    certificate:
    destinationCACertificate:

livenessProbe:
  enabled: false
  path: "" # default is /

readinessProbe:
  enabled: false
  path: "" # default is /

nodeSelector: {}

tolerations: []

affinity: {}

env: 
- name: AB_JOLOKIA_OFF
  value: "true"
- name: AB_PROMETHEUS_OFF
  value: "true"
- name: JAVA_MAX_MEM_RATIO
  value: "95"
- name: JAVA_INIT_MEM_RATIO
  value: "95"
- name: JAVA_OPTIONS
  value: >-
    -Dquarkus.profile=devstage -Djava.net.preferIPv4Stack=true
    -Dquarkus.http.cors.origins=https://mega-zep-frontend-mega.apps.play.gepaplexx.com
- name: TZ
  value: Europe/Vienna
- name: DB_USER
  valueFrom:
    secretKeyRef:
      name: mega-zep-db-pguser-mega
      key: user
- name: DB_PASSWORD
  valueFrom:
    secretKeyRef:
      name: mega-zep-db-pguser-mega
      key: password
- name: DB_HOST
  valueFrom:
    secretKeyRef:
      name: mega-zep-db-pguser-mega
      key: host

volumes:
- name: secret
  secret:
    secretName: mega
    defaultMode: 420
    items:
    - key: .env
      path: .env

volumeMounts:
- name: secret
  mountPath: /deployments/.env
  subPath: .env

resources:
  limits:
    cpu: 750m
    memory: 800Mi
  requests:
    cpu: 250m
    memory: 400Mi

secret:
  enabled: true
  name: mega
  data: 
    .env: >-
      VE9LRU49YzBjMzgzNDM0Njk4ZDI2OTYxNjNmMjgwN2FjYmYyZDlmMzFlOWVjYjE4NzU1YjRlYzQzZjUwMTMyMzc4OGQ2YgpNQUlMRVJfUEFTU1dPUkQ9cHJ5Y3d2b2ppZXZlc2loZw==