apiVersion: v1
kind: ConfigMap
metadata:
  name: vela-kubeconfig
data:
  config.template: |
    apiVersion: v1
    clusters:
    - cluster:
        server: {{ .Values.kubeconfig.apiUrl }}
      name: ocp-cluster
    contexts:
    - context:
        cluster: ocp-cluster
        namespace: {{ .Release.Namespace }}
        user: argocd-vela-sa
      name: baukasten
    current-context: baukasten
    kind: Config
    users:
    - name: argocd-vela-sa
      user:
        token: $API_TOKEN
