apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gp-bke-runtime-minimal-application.logical.name" . }}
  labels:
    {{- include "gp-bke-runtime-minimal-application.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "gp-bke-runtime-minimal-application.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "gp-bke-runtime-minimal-application.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.ports }}
          ports:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path | default "/" }}
              port: 8080
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path | default "/" }}
              port: 8080
          {{- end }}
          env:
          {{- range .Values.database }}
            - name: {{ .name | upper }}_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .name }}-db
                  {{- if eq .type "mysql" }}
                  key: mysql-password
                  {{- else }}
                  key: password
                  {{- end }}
            - name: {{ .name | upper }}_DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .name }}-db-connect
                  key: username
            - name: {{ .name | upper }}_DB_JDBCURL
              valueFrom:
                secretKeyRef:
                  name: {{ .name }}-db-connect
                  key: jdbcurl
          {{- end }}
          {{- with .Values.env }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if (include "gp-bke-runtime-minimal-application.hasVolumeMounts" .) }}
          volumeMounts:
          {{- include "gp-bke-runtime-minimal-application.volumeMounts" . | nindent 12 }}
          {{- end }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
      {{- if (include "gp-bke-runtime-minimal-application.hasVolumeMounts" .) }}
      volumes:
      {{- include "gp-bke-runtime-minimal-application.volumes" . | nindent 8 }}
      {{- end }}
