#https://docs.openshift.com/container-platform/4.10/monitoring/configuring-the-monitoring-stack.html#configurable-monitoring-components_configuring-the-monitoring-stack
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-workload-monitoring-config
  namespace: openshift-user-workload-monitoring
data:
  config.yaml: |
    prometheus:
      resources:
        requests:
          cpu: {{ .Values.userWorkloadMonitoring.prometheus.resources.requests.cpu }}
          memory: {{ .Values.userWorkloadMonitoring.prometheus.resources.requests.memory }}
        limits:
          cpu: {{ .Values.userWorkloadMonitoring.prometheus.resources.limits.cpu }}
      {{ include "infranodes.enabled" . }}
      volumeClaimTemplate:
        spec:
          storageClassName: {{ .Values.userWorkloadMonitoring.prometheus.storageClassName }}
          resources:
            requests:
              storage: {{ .Values.userWorkloadMonitoring.prometheus.storageSize }}
    prometheusOperator:
      {{ include "infranodes.enabled" . }}
    thanosRuler:
      {{ include "infranodes.enabled" . }}
      volumeClaimTemplate:
        spec:
          storageClassName: {{ .Values.userWorkloadMonitoring.thanosRuler.storageClassName }}
          resources:
            requests:
              storage: {{ .Values.userWorkloadMonitoring.thanosRuler.storageSize }}
