apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-main
  namespace: openshift-monitoring
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  encryptedData:
    alertmanager.yaml: {{ .Values.alertmanager.config }}
  template:
    metadata: {}