---
name: Lint Helm Chart
'on':
  push:
    branches:
      - 'develop'
    tags-ignore:
      - '**'

# TODO: github action f√ºr helm linting herausfinden!
jobs:
  lint-helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Lint Helm
        uses: WyriHaximus/github-action-helm3@v2
        with:
          exec: |
          helm lint \
              ./bke/*/. \
              ./infra/*/.
