---
name: Lint Helm Chart
'on':
  push:
    branches:
      - 'develop'
    tags-ignore:
      - '**'

# TODO: github action f√ºr helm linting herausfinden!
#jobs:
#  release:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Publish Helm charts
#        uses: stefanprodan/helm-gh-pages@master
#        with:
#          token: ${{ secrets.PAT }}
#          charts_dir: .
#          charts_url: https://gepaplexx.github.io/gp-helm-charts/
#          owner: gepaplexx
#          repository: gp-helm-charts
#          branch: main
