google:
  enable: true
  k8secretName: google-oauth-secret
  clientId: {}
  restrDomain: {}
  clientSecret: {}

git:
  enable: true
  k8secretName: github-oauth-secret
  clientId: {}
  restrOrgs: []
  clientSecret: {}

htpasswd:
  enable: false
  k8secretName: htpass-secret
  data: {}

ldap:
  enable: true
  k8secretName: ldap-secret
  bindPassword: {}
  bindDN: {}
  ldapUrl: {}
